增加博客类型，xss攻击拦截
stick-i/scblogs pull request #101
Opened 2022-10-26 13:50 UTC by sLiKangli

需要执行sql脚本

alter table blog.blog
    add create_type int(1) null comment '博客创作类型：1. 原创; 2. 转载';

@stick-i

2022-10-28 13:38 UTC, stick-i commented
SQL的修改可以提交到document文档里面的SQL语句当中噢，直接在创建表的SQL语句上修改即可

2022-10-28 13:45 UTC, stick-i commented
当前新增的功能应该提交到dev分支，我根据你提的issue单独开了一个dev分支噢

![image](https://user-images.githubusercontent.com/67500171/198620341-585058ef-b6c7-40e9-aa74-929f98c5718d.png)


分支的名称为 [dev_blog_#100](https://github.com/stick-i/scblogs/tree/dev_blog_%23100)，你当前的代码应该合并到这个分支上。

2022-10-28 14:34 UTC, stick-i requested changes
请提交到dev_blog_#100分支上噢

2022-10-28 14:34 UTC, stick-i commented on blog-service/blog-server/src/main/java/cn/sticki/blog/pojo/bo/BlogSaveBO.java
> +	Integer createType;
其实还有好几个pojo类需要加上这条属性

2022-10-28 14:34 UTC, stick-i commented on common/common-web/src/main/java/cn/sticki/common/web/advice/DefaultExceptionAdvice.java
> +			message = "参数异常:" + e.getMessage();
这样校验是否会导致某些非人为控制抛出IllegalArgumentException的地方，会将异常信息返回到前端？

2022-10-28 14:34 UTC, stick-i commented on common/common-web/src/main/java/cn/sticki/common/web/filter/XssFilter.java
> +public class XssFilter implements Filter {
Xss过滤的效果可否贴几张效果图到pr中。如果没问题的话，我觉得这块其实可以放到网关当中。

2022-10-29 06:10 UTC, sLiKangli commented on common/common-web/src/main/java/cn/sticki/common/web/advice/DefaultExceptionAdvice.java
> +			message = "参数异常:" + e.getMessage();
如果有非我们显示调用抛出的IllegalArgumentException异常，说明是代码bug,需要修复，现在这个单独处理，是因为使用了spring的Assert 断言类，message描述了异常原因，需要主动抛给前端，进行友好提示。
也可以考虑自己创建断言类，自定义异常，不用或继承IllegalArgumentException

2022-10-29 06:14 UTC, sLiKangli commented on blog-service/blog-server/src/main/java/cn/sticki/blog/pojo/bo/BlogSaveBO.java
> +	Integer createType;
BlogDoc 和 Blog 类有加

2022-10-29 06:48 UTC, closed without merging